<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Attributes
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['ATTRIBUTES']['isotope'] = array('Isotope eCommerce','Dieses Attribut fügt eine im Backend eine Auswahl zu einem bestehenden Isotope Produkt ein. Die Frontend-Ausgabe liefert den Warenkorb-Button.');