<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Attributes
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['ATTRIBUTES']['isotope'] = array('Isotope eCommerce','This attribute adds a product selection in the backend and renders the "Add to cart" button to the front end.');